services:

  webapp:
    build: .
    environment:
      DEFAULT_PASSWORD: ${DEFAULT_PASSWORD}
      NODE_EXTRA_CA_CERTS: ${NODE_EXTRA_CA_CERTS}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
      GITHUB_ZENODO_WEBHOOK: ${GITHUB_ZENODO_WEBHOOK}
    restart: unless-stopped
    volumes:
      - pf_uploads:/home/node/app/uploads
      - pf_output:/home/node/app/output
    secrets:
      - rsa-private-key
    depends_on:
      - mariadb
    ports:
      - 3003:3003

  mariadb:
    build: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - pf_data:/var/lib/mysql
    restart: unless-stopped

  migration:
    image: importer-webapp:latest
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    secrets:
      - rsa-private-key
    command: ["./bin/wait-for-it.sh", "--timeout=0", "mariadb:3306", "--", "npm", "run", "migrate"]
    depends_on:
      - mariadb
      - webapp

volumes:
  pf_uploads:
  pf_output:
  pf_data:

networks:
  default:
    name: hi_default # For proxy.
    external: true

secrets:
  rsa-private-key:
    file: ${RSA_PRIVATE_KEY_FULL_PATH}
